### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAutoDoc' of undefined

### ISSUE THREAD

**Issue by devinmcgloin** [sjlevine/atom-slime#1]
Hi Steve, 

This error keeps on popping up when I have the following code from the practical common lisp book in the editor:
```
(defvar *count* 0 
  "Count of widgets made so far.")

(defparameter *gap-tolerance* 0.001  
  "Tolerance to be allowed in widget gaps.")
```
I figured it was an issue with doc strings, but it could be me not knowing what I'm doing. 
Thanks for the awesome package, I just won't use doc strings for now!

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-slime](https://github.com/sjlevine/atom-slime) package, v1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getAutoDoc' of undefined

```
At /Users/devinmcgloin/.atom/packages/atom-slime/lib/atom-slime-editor.coffee:39

TypeError: Cannot read property 'getAutoDoc' of undefined
  at AtomSlimeEditor.module.exports.AtomSlimeEditor.processCursorMoved (/Users/devinmcgloin/.atom/packages/atom-slime/lib/atom-slime-editor.coffee:39:25)
  at /Users/devinmcgloin/.atom/packages/atom-slime/lib/atom-slime-editor.coffee:31:42

```

### Commands

```
     -0:28.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:17.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -0:15.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:10.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:09.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.7.0 slime:connect (atom-text-editor.editor)
     -0:04.2.0 lisp-paredit:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/devinmcgloin/projects",
    "disabledPackages": [
      "pigments",
      "linter-javac",
      "language-ipynb",
      "autocomplete-python",
      "color-picker",
      "language-prolog",
      "language-scala",
      "markdown-pdf"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-slime, v1.3.0
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.1
ide-haskell, v0.6.0
language-haskell, v1.1.6
language-lisp, v0.1.2
language-rust, v0.4.3
linter, v1.1.0
linter-rust, v0.2.1
lisp-paredit, v0.3.1
minimap, v4.10.2
minimap-autohide, v0.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pdf-view, v0.22.0
tabs-to-spaces, v0.11.0
tidy-markdown, v1.0.0
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by sjlevine** [comment]
Hi Devin,

Thanks for your detailed bug report - I believe it should be fixed as of v1.5.0! When you get a chance, could you please update & verify it's fixed?

The `atom-slime` package is still quite new and under active development - just started working on it about two weeks ago. Please don't hesitate to let me know if you find anything strange.

Happy 4th!

Cheers,
Steve

**Comment by sjlevine** [comment]
Also! I think was a bug in the package's communication protocol, not actually in your use of docstrings.

**Comment by devinmcgloin** [comment]
Hi Steve, 

Everything seems to be working well now! Thanks for the quick fix. 

I'm not all that familiar with the emacs slime package, but auto complete and hover documentation would be kind of neat. I'm just starting to learn lisp and I've found the biggest problem being learning what methods are included with `sbcl` and what methods are for other lisp dialects. But perhaps an autocomplete would be outside the scope of the package. 

I'll let you know if I find anything else that's odd! 

Thanks, 
Devin

**Comment by sjlevine** [comment]
Hi Devin,

I completely agree with you. Autocomplete and hover documentation are not at all outside the scope of this package, would be super useful, and are definitely on my to-do list.

Even though "hover documentation" isn't there yet, there is something implemented now that could be useful to you as you learn Lisp. After you're connected to Slime, and if you're editing a Lisp buffer, putting the cursor over an s-expression should bring up the argument order to that expression in the status bar. It's a start!

Cheers,
Steve
