### ISSUE TITLE
Weird Crash With #\

### ISSUE THREAD

**Issue by haz** [sjlevine/atom-slime#12]
Opening a new file, saving it with a .lisp extension (to enable Lisp mode), and then typing this seems to crash the interpreter:

```
(ql:quickload "split-sequence")

(split-sequence:split-sequence #\)
```

It occurs just as you type the `\`

**Comment by sjlevine** [comment]
Good catch! Turns out that that `\` was the problem; I wasn't escaping my strings properly before sending them off to lisp. Should be fixed!
