### ISSUE TITLE
Cyrillic symbols in REPL crashes slime connection

### ISSUE THREAD

**Issue by avknor** [sjlevine/atom-slime#18]

**Comment by cbaggers** [comment]
Can confirm and extend to say many unicode characters fail. 

paste λ in the repl to trigger crash

**Comment by sjlevine** [comment]
Thanks for reporting this! This issue should now be fixed in the latest version.

**Comment by cbaggers** [comment]
Woo thanks, will go check it out now

**Comment by avknor** [comment]
great!
