### ISSUE TITLE
[Bug] Restarting slime spawns extra listener

### ISSUE THREAD

**Issue by RyanHope** [sjlevine/atom-slime#19]
If you already have a listener open and restart slime, a new window is created instead of reusing the one that is already open.

**Comment by sjlevine** [comment]
Hi Ryan, on my machine, the older REPL stays open when I restart slime, but it's really a REPL as it's not connected to Lisp yet - it's merely a texteditor showing your last session. Upon starting slime again, it re-uses that buffer. Is that the behavior you're seeing?

**Comment by sjlevine** [comment]
This should be fixed as of https://github.com/sjlevine/atom-slime/commit/f99e57bd015aefa37563c037cab3620c2023f46f -- please update to the latest `atom-slime`. Feel free to re-open this issue if you're still having a problem. Thanks!
