### ISSUE TITLE
atom-slime won't compile file

### ISSUE THREAD

**Issue by MyCodeSnips** [sjlevine/atom-slime#25]
Hello,

I'm running atom on OSX 10.11.5

I've installed atom-slime and associated packages as indicated in the documentation. I have a working sbcl REPL but when I place cursor in a .lisp file and hit alt-c, nothing happens. Also, within atom in the Packages->Slime submenu, only "Start", "Disconnect" and "Restart" show up. The is no "goto-definition" or "compile-function" corresponding to alt-. and alt-c key combinations respectively.

**Comment by sjlevine** [comment]
Strange, haven't seen this! Thanks for reporting. Sounds like the atom-slime package may not be properly identifying your file as a lisp file, and adding the special magic to that text editor to make these things above work.

Can you verify if your file is being identified properly as a lisp file? You'd see "Lisp" in the lower right corner of Atom. Saving it with a ".lisp" at the end should definitely make it happen.

**Comment by sjlevine** [comment]
I was just able to reproduce this - it should be fixed. Please reopen if it continues to be an issue!
