### ISSUE TITLE
Alt+C Not Working

### ISSUE THREAD

**Issue by itsdanielmatos** [sjlevine/atom-slime#50]
Hi,

I followed the tutorial to prepare my computer to work with LISP but after the tutorial I cant compile functions. This was the tutorial: https://atom.io/packages/atom-slime

Thanks in advance,

itsdanielmatos.

**Comment by sjlevine** [comment]
Hi Daniel, what OS are you running? Does the REPL / terminal work?

**Comment by itsdanielmatos** [comment]
I fixed it @sjlevine,  it was someting about coffeescript. Sorry for late answer. Issue Closed
