### ISSUE TITLE
Lisp REPL won't start, editors have no tabs

### ISSUE THREAD

**Issue by jarecsni** [sjlevine/atom-slime#51]
Just installed Atom and atom-slime, following the description (on a macOS Sierra). 

When I launch the REPL with Packages:Slime:Start this is what I end up with:
![screen shot 2016-12-17 at 19 05 19](https://cloud.githubusercontent.com/assets/2016918/21289102/f4fe6bcc-c48b-11e6-986c-ba6221fa1c00.png)

Also, as you can see there's no tab on the editors for some reason (which works fine with Javascript source files). Sometimes I can make it work, but until now I didn't notice any pattern (I do play with setting the theme and that seems to help sometime).

I'd appreciate any help, thanks.

**Comment by jarecsni** [comment]
I've managed to get it working using the same workaround described here: [https://github.com/sjlevine/atom-slime/issues/49](https://github.com/sjlevine/atom-slime/issues/49)

**Comment by haz** [comment]
Thanks...resolving this as a duplicate, and we'll get the associated merge request put in by the end of the weekend. Cheers!

**Comment by sjlevine** [comment]
Thanks for reporting this!
