### ISSUE TITLE
Deprecated selector in `atom-slime/styles/atom-slime.less`

### ISSUE THREAD

**Issue by haz** [sjlevine/atom-slime#52]
**Preface**: This issue was automatically generated from the Atom Beta release.

In `atom-slime/styles/atom-slime.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .repl-prompt` => `atom-text-editor.editor .syntax--repl-prompt`

* `atom-text-editor::shadow .repl-line` => `atom-text-editor.editor .repl-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by sjlevine** [comment]
Hey Christian, thanks for reporting this! 

I actually already fixed this issue -- it's the one related to the shadow DOM that I mentioned briefly to you yesterday, that will only work with the 1.13 beta version of Atom. It's fixed in commit https://github.com/sjlevine/atom-slime/commit/4e54e636c2368da28b7ac73e4d9d1ffcdd0ce5c1, which right now is living in the separate `shadowdom` branch and will be merged into master once Atom beta 1.13 is no longer beta.

**Comment by sjlevine** [comment]
Actually I'll leave this issue open as a reminder to actually merge into master. Thanks!

**Comment by haz** [comment]
Aye, just wanted to have the issue open until resolved in the public version.

We discussed the minimum atom version setting, but how does one maintain multiple versions? And just to be sure, the fix for v1.13.0 isn't backwards compatible, is it? If so, we could just merge now...

**Comment by sjlevine** [comment]
Indeed, it's not backwards compatible. Not sure how Atom actually handles it behinds the scene, but I assume they'd install the latest released version of a package compatible with their atom version?

**Comment by haz** [comment]
I see. Well unless we only want to develop for the beta (so master branch is targeting that), it may be difficult to maintain two versions.

What about just keeping a beta-ready branch (constantly updated from master) that will be merged in once atom ticks up the stable version? Sort of what you already have with the shadow-dom branch, but generalized to capture everything that might break with the update to the new api's.

**Comment by sjlevine** [comment]
I like the idea of a `beta` branch. Done -- https://github.com/sjlevine/atom-slime/tree/beta

**Comment by sjlevine** [comment]
This has been merged into master, so closing issue.
