### ISSUE TITLE
REPL doesn't start

### ISSUE THREAD

**Issue by wolfadex** [sjlevine/atom-slime#57]
After running slime-start I get the message to wait a moment and run slime-connect. After waiting a moment I run slime-connect and successfully connect to the swank server, however no REPL ever shows.

In the dev tools console I do see 1 error message: `Error constructing command: TypeError: Cannot read property 'replace' of undefined` coming from `.../.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:259`.

Mac OS X 10.11.4
Atom 1.1.5.0

**Comment by wolfadex** [comment]
It looks like an issue with slime v2.19 and v2.18. I can get the REPL to show when using slime v2.17.

**Comment by sjlevine** [comment]
Strange, I can get the REPL to work properly with slime v2.19. Are you using SBCL? I haven't tried on Mac yet.

**Comment by wolfadex** [comment]
I am using SBCL. I've gotten it to work on Linux without issue, so my guess is it's something Mac related.
