### ISSUE TITLE
Compile this function

### ISSUE THREAD

**Issue by lengbing** [sjlevine/atom-slime#6]
I am dying for feature 'Compile this function'! Please add it. Thank you!

**Comment by sjlevine** [comment]
I agree this would be a very useful feature! It is definitely on my to-do list. That said, I'm just one person working on this in my spare time. Feel free to submit a pull request for the feature and I will look it over!

**Comment by sjlevine** [comment]
Hello, support for this feature has been added! Please update `atom-slime` and let me know what you think. I still haven't added "Compile this file", but it's also on my to-do list.
