### ISSUE TITLE
Proper spaces

### ISSUE THREAD

**Issue by Sokolov57** [sjlevine/atom-slime#64]
Hello, and, foa, thanks for your great work. Very excited to be able to use my favorite text editor with lisp. But I have this little annoying thing -- in repl instead of spaces and instead of anything that is supposed to be just nothing it writes this things []. I definetly have proper white spaces in every other place, so I d say this is some package specific problem.
Any ideas?

**Comment by vindarel** [comment]
Hi, it must be a pb on your side. My output is correct:

![selection_201](https://user-images.githubusercontent.com/3721004/34740209-e1e7b1fe-f57e-11e7-999b-8cd48dec5c43.png)
