### ISSUE TITLE
FEATURE - Question "atom-in-orbit"

### ISSUE THREAD

**Issue by prologmud** [sjlevine/atom-slime#70]
Does this atom package work with any atom in a web page?

for example https://github.com/facebook-atom/atom-in-orbit

**Comment by sjlevine** [comment]
Hello! This package has not been tested in that sort of setting. From a cursory glance, I'm not sure if the socket / network aspect of the `swank-client-js` library (which is required by this package) would work, due to browser limitations.

Good luck!

**Comment by vindarel** [comment]
no idea (did you try?) but atom-in-orbit seems staling.
