### ISSUE TITLE
TextBuffer.setTextInRange is deprecated.

### ISSUE THREAD

**Issue by mlg556** [sjlevine/atom-slime#74]
The `undo` option is deprecated. Call groupLastChanges() on the TextBuffer afterward instead.
```
TextBuffer.setTextInRange (<embedded>:33539:22)
TextEditor.setTextInBufferRange (<embedded>:3552:35)
REPLView.setPromptCommand (/Users/oolonthegreat/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:355:26)
REPLView.showPreviousCommand (/Users/oolonthegreat/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:345:21)
REPLView.cycleBack (/Users/oolonthegreat/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:329:19)
HTMLElement.subs.add.atom.commands.add.core:move-up (/Users/oolonthegreat/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:143:21)
```

**Comment by Weatherbee** [comment]
TextBuffer.setTextInRange - <embedded>:11:487502
TextEditor.setTextInBufferRange - <embedded>:11:15252
REPLView.setPromptCommand - /Users/jamil/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:355:26
REPLView.showPreviousCommand - /Users/jamil/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:345:21
REPLView.cycleBack - /Users/jamil/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:329:19
HTMLElement.subs.add.atom.commands.add.core:move-up - /Users/jamil/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:143:21
