### ISSUE TITLE
Doesn't support ~ in file paths

### ISSUE THREAD

**Issue by mohe2015** [sjlevine/atom-slime#83]
The Slime Path can't contain ~ to reference the home directory. This should work or at least show an error that's more meaningful than that the slime path directory can't be opened.

**Comment by neil-lindquist** [comment]
Atom-Slime is not really being actively maintained right now.  [SLIMA](https://github.com/neil-lindquist/slima) is the active fork currently.  I opened issue [#15](https://github.com/neil-lindquist/SLIMA/issues/15) for this.
